language: scala
script:
  - sbt publishLocal
scala:
   - 2.12.3
jdk:
   - oraclejdk8
before_script:
  - mkdir $TRAVIS_BUILD_DIR/tmp
  - export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"
sudo: false
